spring:
  session:
    store-type: hazelcast

zuul:
  routes:
    wicket:
      path: /**
      serviceId: wicketservice

wicketservice:
  ribbon:
    listOfServers: localhost:8081,localhost:8082